#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-ss-whs1','console_scripts','double_whs1_control'
__requires__ = 'tms-ss-whs1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-ss-whs1', 'console_scripts', 'double_whs1_control')()
    )
