#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-rc-double','console_scripts','convert_twist2vector3'
__requires__ = 'tms-rc-double'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-rc-double', 'console_scripts', 'convert_twist2vector3')()
    )
