#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-ur-listener','console_scripts','tms_ur_listener_server'
__requires__ = 'tms-ur-listener'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-ur-listener', 'console_scripts', 'tms_ur_listener_server')()
    )
