#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-db-manager','console_scripts','tms_db_reader'
__requires__ = 'tms-db-manager'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-db-manager', 'console_scripts', 'tms_db_reader')()
    )
