#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-ts-ts','console_scripts','tms_ts_master'
__requires__ = 'tms-ts-ts'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-ts-ts', 'console_scripts', 'tms_ts_master')()
    )
